### PR TITLE
CSHARP-2687: Reduced allocations during deserialization

### PR DESCRIPTION
**Pull request by dnickless**
This PR fixes https://jira.mongodb.org/browse/CSHARP-2687

### CODE REVIEW

**Review by BorisDog — APPROVED** [review]

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Comment by DmitryLukyanov** [comment]
Thanks, @dnickless!

**Review by rstam — APPROVED** [review]
LGTM

**Comment by BorisDog** [comment]
[EG](https://evergreen.mongodb.com/version/5feb9db9562343703448c517) [Internal Link]

**Comment by BorisDog** [comment]
[Merged](https://github.com/mongodb/mongo-csharp-driver/commit/4e2a5df68146c5cdf5ee85758ddaac688b63e794)

**Pull request closed without merging**
