### PR TITLE
CSHARP-3996: Fix cleanup-test-resources on Linux and Macos.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**
EG: https://evergreen.mongodb.com/version/61b7e7463627e00295e8b335

### CODE REVIEW

**Review by JamesKovacs — CHANGES_REQUESTED** [review]
We are missing the shebang (`#!`) for `get-python-path.sh`, `set-temp-fle-aws-creds.sh`, and `set-virtualenv.sh` as well. We also have a mix of `#!/bin/bash` and `#!/usr/bin/env bash`. We should standardize on the latter. Let's update CSHARP-3996 to fix all these issues.

**Comment by DmitryLukyanov** [comment]
EG: https://evergreen.mongodb.com/version/61b893fda4cf470453bbcda5

**Comment by DmitryLukyanov** [comment]
ready for review

**Review by JamesKovacs — APPROVED** [review]
LGTM

**Pull request merged**
