### PR TITLE
CSHARP-5209: remove-aws-sdk-from-deps

### PR DESCRIPTION
**Pull request by barnuri**
https://jira.mongodb.org/browse/CSHARP-5209
cant upgrade my mongo driver because i have references to aws sdk, and its not in match with your reference, also its look like the reference for aws its only for ut, so i move it to the ut project

### CODE REVIEW

**Comment by barnuri** [comment]
@rstam @sanych-sun @adelinowona @jameswahlin someone can take a look ?

**Comment by sanych-sun** [comment]
Closed, as this is a part of bigger development to separate AWS-related code into new package.

**Comment by barnuri** [comment]
> Closed, as this is a part of bigger development to separate AWS-related code into new package.

there is ETA ?

**Comment by barnuri** [comment]
will be solved in https://jira.mongodb.org/browse/CSHARP-4911

**Comment by barnuri** [comment]
> Closed, as this is a part of bigger development to separate AWS-related code into new package.

short solution until you going to break the nuget, support lower version of aws nuget
https://github.com/mongodb/mongo-csharp-driver/pull/1401

**Pull request closed without merging**
