### PR TITLE
CSHARP-3756: Set minWireVersion to 6 (MongoDB 3.6)/CSHARP-3867: Bump maxWireVersion to 14 for MongoDB 5.1.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**

### CODE REVIEW

**Review by jyemin — CHANGES_REQUESTED** [review]
You're going to need to also disable the Evergreen tests of 2.6-3.4.

**Comment by DmitryLukyanov** [comment]
> 
> 
> You're going to need to also disable the Evergreen tests of 2.6-3.4.

done

**Review by jyemin — APPROVED** [review]
LGTM

**Review by rstam — APPROVED** [review]
LGTM

**Pull request merged**
