### PR TITLE
CSHARP-1942: Reducing delegate allocations

### PR DESCRIPTION
**Pull request by onyxmaster**
https://jira.mongodb.org/browse/CSHARP-1942

### CODE REVIEW

**Comment by BorisDog** [comment]
Thanks @onyxmaster for this contribution.
The similar optimization in BsonWriter.cs is applied [here](https://github.com/BorisDog/mongo-csharp-driver/commit/7c3c5caf53366c16df1bf0108e20b674c0b5647f).

The optimization in BsonSerializerRegistry.cs looks good. Could you please rebase and leave the BsonSerializerRegistry.cs changes?

**Comment by onyxmaster** [comment]
Messed up the rebase at first, but I think I got it right the second time.

**Review by BorisDog — APPROVED** [review]

**Review by JamesKovacs — APPROVED** [review]
Reviewed memory pressure metrics from test case to confirm that the change results in many fewer `Func<Type, IBsonSerializer>` allocations. LGTM.

**Comment by BorisDog** [comment]
[EG](https://evergreen.mongodb.com/version/5fff419fa4cf4737acf6aeee) (Internal link)

**Comment by BorisDog** [comment]
Thanks @onyxmaster! Merged [here](https://github.com/mongodb/mongo-csharp-driver/commit/3c647cef34cbde016aa91b41499e041d68ef93df).

**Pull request closed without merging**
