### PR TITLE
CSHARP-2066 Serialization of positional operator now culture-insensitive

### PR DESCRIPTION
**Pull request by johnknoop**
Please see my comment in the Jira ticket. I wasn't able to edit the description, so I put all the info in a comment:

https://jira.mongodb.org/browse/CSHARP-2066

### CODE REVIEW

**Comment by BobCochran** [comment]
This request would seem to require also changing the documentation to discuss the positional operator. I do not see where the operator is documented. I believe the change will need extensive testing prior to merging. This change is effectively being offered without any significant unit testing.

**Comment by johnknoop** [comment]
Hi again @BobCochran 

It for sure needs the appropriate quality checking. I only tested the scenario we discussed in the Google group:

```
await collection.UpdateOneAsync(
	filter: x => x.Id == "5ba573631f138fe8f4c9a3dd" && x.Species.Relatives.Any(r => r.Name == "Lion"),
	update: Builders<Animal>.Update.Inc(y => y.Species.Relatives[-1].Population, 5)
);
```

I would gladly cover this with some unit tests, if I'm allowed to do some refactoring to enable testability?

**Comment by johnknoop** [comment]
I factored out the string formatting to a new class, and added some unit tests that verifies the behaviour of it.

However, reverting `FieldExpressionFlattener.cs` will not make the tests fail, unless you run it in .NET Core on Linux. The string comparison of "-1" and "-1" never failed on Windows, so these tests are kind of unrelated to the root issue that I solved in this PR.

**Comment by johnknoop** [comment]
@rstam @craiggwilson it would be great if this got merged pretty soon, as it's currently a blocker for us. Is there something I can do you expedite this? Do you want me to prodive you with a test solution that you can run to reproduce the issue?

**Comment by johnknoop** [comment]
I've created a project that let's you reproduce the bug. Just follow the instructions in the readme: https://github.com/johnknoop/mongodb2066

**Comment by DmitryLukyanov** [comment]
Thank you for the pull request! I've merged the changes based on your PR into the master.

**Pull request closed without merging**
