### PR TITLE
CSHARP-4028: Reduced allocations by eliminating a lambda closure

### PR DESCRIPTION
**Pull request by dnickless**
As per https://jira.mongodb.org/browse/CSHARP-4028

### CODE REVIEW

**Comment by rstam** [comment]
This change looks fine to me and is low-risk. @JamesKovacs I've added you as a reviewer so you can give your opinion also.

**Review by JamesKovacs — APPROVED** [review]
LGTM.

Note: There are other instance methods that can be made static in this class, but they aren't used in the context of a lambda. Changing this one will suffice.

**Review by rstam — APPROVED** [review]
LGTM

**Comment by rstam** [comment]
Rebased on master and merged.

**Pull request closed without merging**
