### PR TITLE
Solve issue in .net core 2.0

### PR DESCRIPTION
**Pull request by kimiko88**
NU1605 issue could happen when you test a project that use mongoDB.Driver.Core library

### CODE REVIEW

**Comment by BigFishVN** [comment]
Can you please merge this pull request to fix NU1605 issue? I can't publish my app which was use net core 2 with MongoDB.Driver 2.4.4

**Comment by rstam** [comment]
Can you please explain how this change resolves the problem?

The existing dependency on System.Runtime.InteropServices.RuntimeInformation is on version >= 4.0.0. Why does that not already work?

**Comment by BigFishVN** [comment]
@rstam I created [a sample project](https://github.com/BigFishVN/mongo-netcore2-error) to show the errors when used _dotnet --publish -r (Windows RID)_. The NU1605 happens after I referenced [Microsoft.AspNetCore.Authentication](https://github.com/aspnet/Security) **(2.0.0)**. Hope this sample may help to solve the problem.

**Comment by BigFishVN** [comment]
I found the problem. With Visual Studio 2017, project.json is [no longer available](https://docs.microsoft.com/en-us/dotnet/core/tools/cli-msbuild-architecture). The project properties treat warnings as errors contain NU1605 as default, which you can see in the image below:
capture
I can bypass this error by select "None" and can publish the app. Hope the next version of MongoDB.Driver will remove this warning as default.

**Comment by jyemin** [comment]
Hi @kimiko88 I think we've fixed this in a subsequent release, but if not please open a Jira issue to discuss it further.

**Pull request closed without merging**
