### PR TITLE
CSHARP-1809: Mockable GridFSDownloadStream and GridFSUploadStream

### PR DESCRIPTION
**Pull request by brian-pickens**
Resolve CSHARP-1809 to make these types mockable

### CODE REVIEW

**Comment by brian-pickens** [comment]
How do I get this pull request considered?

**Comment by BorisDog** [comment]
Hi @brian-pickens, thank you for your PR.

We are looking into this pull request and CSHARP-1809 ticket.
Please follow CSHARP-1809 for any updates.

**Comment by BorisDog** [comment]
Hi @brian-pickens ,
The suggested changes look good, and all tests pass.

Could you please rebase to the latest master and squash commits into a single one?

**Comment by JamesKovacs** [comment]
Hi, Brian,

Thank you for contributing to the MongoDB .NET/C# Driver. I have cherrypicked your changes onto `master` and they will be available in the next release.

Please note that we do not recommend or encourage mocking third-party dependencies such as the driver. Much has been written on the subject by TDD/BDD practitioners over the years and why it is considered an anti-pattern. If you feel the need to mock a third-party dependency, it is often better to wrap it in an adapter allowing you to mock the adapter (which you do own) and integration test the adapter with the actual dependency.

James

**Pull request closed without merging**
