### PR TITLE
CSHARP-4517: Values being compared must be of the same type.

### PR DESCRIPTION
**Pull request by rstam**

### CODE REVIEW

**Review by JamesKovacs — APPROVED** [review]
LGTM

**Review by JamesKovacs — COMMENTED** [review]
There are a lot of LINQ2 test failures in the patch build - which doesn't make immediate sense to me as the code changes are in LINQ3. Please investigate these failures before merging.

**Review by JamesKovacs — CHANGES_REQUESTED** [review]
Changes look good but the patch build is showing a lot of LINQ2 failures, which don't make sense to me as the changes were isolated to LINQ3 code. Please investigate before merging.

**Comment by rstam** [comment]
The tests that are failing are not LINQ2 test but rather Linq2ImplementationTestsOnLinq3 tests.

I'm going to have to rework this fix.

I'll re-request your review when it's ready.

**Comment by rstam** [comment]
Looks like it was sufficient to relax the requirement that operands be of the *same* type to just require that they be of *compatible* types, where compatible means one of:

* one operand is null
* both operands are the same type
* one operand can be implicitly converted to the other

**Review by JamesKovacs — APPROVED** [review]
LGTM

**Pull request merged**
