### PR TITLE
CSHARP-3941: ToString for "FilterDefinition" and "SortDefinition"

### PR DESCRIPTION
**Pull request by bernd5**
Added a simple "ToString()" override for "FilterDefinition" and "SortDefinition"

### CODE REVIEW

**Comment by bernd5** [comment]
This fixes not a bug but provides a reasonable ToString implementation for these two classes similar to other Definition-classes (like Pipelinedefinition)

**Comment by bernd5** [comment]
@BorisDog: I created a JIRA ticket...

**Comment by rstam** [comment]
See comments in the JIRA ticket (including expanding the scope of this work to include all definition classes at the same time).

**Comment by JamesKovacs** [comment]
With the addition of LINQ3, this PR requires more work. We have closed this PR and we will track the work in [CSHARP-3941](https://jira.mongodb.org/browse/CSHARP-3941).

**Pull request closed without merging**
