### PR TITLE
CSHARP-4646: Support namespace queries in ChangeStreamDocument pipelines.

### PR DESCRIPTION
**Pull request by rstam**

### CODE REVIEW

**Review by sanych-sun — APPROVED** [review]

**Comment by JamesKovacs** [comment]
The following test is failing on MongoDB 3.6:

`MongoDB.Driver.Tests.Jira.CSharp624.CSharp4646Tests.MongoDB.Driver.Tests.Jira.CSharp624.CSharp4646Tests.Watch_database_filtering_on_collection_name`

We also have some other variant failures, which should be investigated.

**Comment by rstam** [comment]
> The following test is failing on MongoDB 3.6:
> 
> `MongoDB.Driver.Tests.Jira.CSharp624.CSharp4646Tests.MongoDB.Driver.Tests.Jira.CSharp624.CSharp4646Tests.Watch_database_filtering_on_collection_name`
> 
> We also have some other variant failures, which should be investigated.

 MongoDB.Driver.MongoCommandException : Command aggregate failed: cannot open $changeStream for non-existent database: test.

Looks like 3.6 requires that the database exist before you can watch it?

**Review by JamesKovacs — APPROVED** [review]
LGTM

I checked the 3 variant failures. All 3 are a result of failing to download `dotnet-install.sh` or `dotnet-install.ps1` because the server returned a 503 unavailable. Annoying, but not due to our code changes.

**Review by sanych-sun — APPROVED** [review]
LGTM

**Pull request merged**
