### PR TITLE
Use DirectoryBuild.props & set SourceLink flags

### PR DESCRIPTION
**Pull request by buvinghausen**
The SourceLink setup is not done correctly.  I've gone ahead and hoisted all the common properties from the various .csproj files in your src folder to use the Directory.Build.props file and set it up set the required fags on your next release.

You can verify the setup is incorrect at [NuGet Package Explorer](https://nuget.info/packages/MongoDB.Driver/2.18.0)

Since I cannot tell what CI system you are using I have it set the ContinuousIntegrationBuild setting when it is built in release mode.  Clearly we can tweak that setting to what you need.

### CODE REVIEW

**Comment by BorisDog** [comment]
Thanks @buvinghausen for noticing this and your PR. Is there anything else incorrect in the SourceLink setup, besides untracked sources warning? If so please open Jira tickets for any other issue. 

Untracked sources fix is tracked in [CSHARP-3994](https://jira.mongodb.org/browse/CSHARP-3994). I've linked this PR to that ticket, please follow it of any further updates.

**Comment by buvinghausen** [comment]
@BorisDog yes you need to set the [ContinuousIntegrationBuild](https://github.com/buvinghausen/mongo-csharp-driver/blob/master/src/Directory.Build.props#L26) flag as well.  I have it set to conditionally only get set on release as I assume you build in release mode as part of your publish to nuget process.  I couldn't tell what CI server/service you use.

**Comment by DmitryLukyanov** [comment]
> @BorisDog yes you need to set the [ContinuousIntegrationBuild](https://github.com/buvinghausen/mongo-csharp-driver/blob/master/src/Directory.Build.props#L26) flag as well. I have it set to conditionally only get set on release as I assume you build in release mode as part of your publish to nuget process. I couldn't tell what CI server/service you use.

Hey @buvinghausen , thanks for this catch. We already configure this option in our build scripts [here](https://github.com/mongodb/mongo-csharp-driver/blob/master/build.cake#L89), but apparently something is broken here. We will investigate this issue in this ticket https://jira.mongodb.org/browse/CSHARP-4384 

> [ContinuousIntegrationBuild](https://github.com/buvinghausen/mongo-csharp-driver/blob/master/src/Directory.Build.props#L26)

**Comment by DmitryLukyanov** [comment]
I've also created a ticket to consider adding build.props to the solution https://jira.mongodb.org/browse/CSHARP-4385. Please follow to that ticket for further discussions

**Comment by sanych-sun** [comment]
Thank you for your contribution. I'll close this Pull Request as already done. Please feel free to reopen it if there are some additional work or help required.

**Comment by sanych-sun** [comment]
I've closed this PR because the proposed changes was mostly implemented by using Directory.Build.props file in scope of [CSHARP-4385](https://jira.mongodb.org/browse/CSHARP-4385).

The issue with untracked sources you have mentioned was separated into additional Jira ticket and was not sorted yet: 
[CSHARP-3994](https://jira.mongodb.org/browse/CSHARP-3994). I haven't approach this problem yet though.

**Pull request closed without merging**
