### PR TITLE
Moving to DNX Project structure to Support CoreCLR

### PR DESCRIPTION
**Pull request by tugberkugurlu**
> **NOTE: THIS IS NOWHERE NEAR READY!**

I have done the initial infrastructure work to move MongoDB.Driver to DNX project structure. This pull request is not here to be merged in as I have done bunch of controversial changes (opps :smile:). However, as the issues section here on GitHub for this project is removed and I wanted to preserve my sanity by not using Jira :trollface:, I am opening this pull request to discuss the CoreCLR support for MongoDB .NET Driver. This is also potentially useful for anyone who is interested in this.

## Why

 - To support CoreCLR.
 - Moving to DNX project structure which will make it easy to develop the project anywhere thanks to OmniSharp powered code editors.

## What I have Done

 - Added **global.json** file to root of the solution to specify project folders and sdk version (beta5) 
 - Added **NuGet.Config** files to root of the solution to specify official nuget feed
 - git-ignored `project.lock.json` files.
 - Moved tests under `test` folder.
 - Moved samples under `samples` folder.
 - Introduced project.json for every project.
 - Made every project successfully compile on `dnx451` target framework.
 - Added the `MongoDB.Driver.sln` file to root of the solution and xproj file for every project to satisfy VS 2015 needs.
 - **Removed legacy project all together as I don't think there is point to maintain them on CoreCLR.**

## What We Need to Do

 - [ ] Make tests work with xUnit and successfully run them.
 - [ ] Add assembly signing stuff.
 - [ ] Make build scripts work with DNX tools to build the project.
 - [ ] Support `dnxcore50` framework target.
 - [ ] Rebase commits.

### CODE REVIEW

**Comment by jtbennett** [comment]
Thanks for starting this. I'd love to help!

**Comment by tugberkugurlu** [comment]
@jtbennett awesome! I think the most sensible thing to do at this stage first is to get tests working with xUnit as it's the only unit testing framework which has DNX support. Not sure if NUnit has it though. However, I am also not sure what to do with FluentAssertions and NSubstitute at the later stages as they don't have `dnxcore50` support.

**Comment by craiggwilson** [comment]
We've thought a little bit about this. Before you guys go off converting tests to use another framework(xUnit, etc...) which would be a whole lot of work, we should have a discussion. I'd hate for you guys to pour a bunch of work into something that doesn't coincide with our needs. For instance, I love xUnit, but we've been using NUnit and it might be better to wait a little bit for them to have .NET core support than to completely switch testing frameworks. .NET Core is still in beta (unless I missed some announcement), so there is still time for our dependencies to include support.

**Comment by tugberkugurlu** [comment]
@craiggwilson let's move NUnit to CoreCLR first then :smile: :trollface: I personally don't care which unit testing framework is being used and I don't think there is much diff between any of them.

I think waiting for CoreCLR to go RTM before starting to move would be too late. I personally care about having MongoDB Driver to be available as soon as CoreCLR has go-live license as I will plan to use this driver on prod in Linux on CoreCLR :disappointed:

**Comment by imperugo** [comment]
:+1: for @tugberkugurlu 

Will be great to have MongoDb Driver (CoreCRL version) almost in the same time of the RTM of CoreCLR

**Comment by SonOfSam** [comment]
I agree with @imperugo , Right now they are delivering a beta version almost every month, these version can include a lot of breaking changes. We are working with a project and we start working with beta 2 so far they are working on beta 6 and we change so much code between each beta release. 

See road map here https://github.com/aspnet/Home/wiki/Roadmap

**Comment by jtbennett** [comment]
Would it make sense to start this in earnest in late September?  They say
that the last beta (8) will be feature complete and released on Sept 21,
with the RC to follow in November. See:
https://github.com/aspnet/home/wiki/roadmap

**Comment by runxc1** [comment]
So not sure if you have been following NUnit but it looks like  NUnit is close to releasing v3 which is a complete re-write and would probably require as much upgrading as moving from NUnit to xUnit

**Comment by sergey-litvinov** [comment]
Just as another possible version, it also can be made to support both nUnit and xUnit. A common attribute `TestAttrtibute` can be made, and it will inherit nUnit's `TestAttribute` or xUnit's `FactAttribute`, and base inheritor class can be specified with `#if CoreCLR`. 

I'm not sure that it's a good way as it's a bit ugly, and also will require supporting of two unit test framework that might be a pain, but at least it won't require waiting while nUnit supports CoreCLR...

nUnit has an issue about adding CoreCLR support in v3 - https://github.com/nunit/nunit/issues/575 , but as CharliePoole says:

>Our use of milestone 3.0 means we would like to get it into the 3.0 final release but that it's not currently planned in any of the betas. Our plates are pretty full.

So there is no any guaranties that it will be shipped with nUnit 3.0

**Comment by tugberkugurlu** [comment]
> I'm not sure that it's a good way as it's a bit ugly, and also will require supporting of two unit test framework that might be a pain, but at least it won't require waiting while nUnit supports CoreCLR...

You will do same amount of upgrade to make that work. Why not move to xUnit then?

**Comment by tugberkugurlu** [comment]
Just wanted to update here that [.NET Core has hit RC1 yesterday](http://www.hanselman.com/blog/ASPNET5AndNETCoreRC1InContextPlusAllTheConnect2015News.aspx) and it has go live license. API changes will be minimum from this point. Not sure if that would make this issue more attractive.

**Comment by rstam** [comment]
The RC1 release of .NET Core is great news. We are planning on targeting .NET Core soon.

**Comment by EvAlex** [comment]
:+1: Great work! We are about to start project on Core CLR and this is really important for us now. What's the status? Is there any possibility to start working right away (experimental branch or something)?

**Comment by jamestoyer** [comment]
@tugberkugurlu What is the status with this? Do you require any help?

**Comment by tugberkugurlu** [comment]
@jamestoyer this issue requires some decisions from the maintainers. From @rstam comment, I understand that they are looking at supporting it but discussions on this don't happen here on Github I assume.

**Comment by alexgwolff** [comment]
There are any info about this? Support CoreCLR is important to me :/

**Comment by rstam** [comment]
We have begun work on this but there are some obstacles to overcome.

We don't yet have a release date for this, but it's more on the order of months than weeks away.

**Comment by tugberkugurlu** [comment]
@rstam It would be really useful if this is being done more openly here on GitHub so that we can also see the progress. It would be a good start to learn more about those obstacles.

**Comment by rstam** [comment]
@tugberkugurlu  we actually do all our work here on github. All changes are made first in a branch on a fork and later merged into the master branch (or other appropriate branch) when ready.

The two forks where you are most likely to see work being done are:

https://github.com/rstam/mongo-csharp-driver
https://github.com/craiggwilson/mongo-csharp-driver

The most recent work related to porting to .NET Core is on this branch:

https://github.com/rstam/mongo-csharp-driver/commits/csharp1504

Which is related to this JIRA ticket:

https://jira.mongodb.org/browse/CSHARP-1504

At this point in this work what we are doing is using the .NET Portability Analyzer against the BSON library to identify where we are using APIs that are not supported by .NET Core and coding around them. This is a good starting point because it gets us closer to where we need to be while still developing against .NET 4.5 where all the tooling is stable (and where we can run our unit tests!).

I've found attempting to use the tooling for .NET Core frustrating and am hoping that things will soon settle down and be stable and well documented. We are also dependent on some third party libraries for our unit tests that need to support .NET Core first, although there has been some progress on that front recently. NUnit 3.0 has partial support for .NET Core (limited to running tests from the command according to the release notes), FluentAssertions release notes claim support for .NET Core, but NSubstitute apparently does not yet support .NET Core (and may in turn be waiting on some of their third party dependencies to support .NET Core).

**Comment by AlexZeitler** [comment]
I agree with @tugberkugurlu. I'm just starting another long term project which should use CoreCLR and MongoDb. Having an unstable driver would be better than having nothing. Node.js is not an option in this particular case and .NET 4.6 neither is.

**Comment by ah-** [comment]
How is this going? Any progress?

**Comment by rstam** [comment]
Yes. We have been making progress.

The main obstacles remain that some of our dependencies do not yet support .NET Core.

NUnit partially supports .NET Core, but has very poor support for actually running tests against .NET Core.

NSubstitute doesn't seem like it's likely to support .NET Core any time soon...

We are considering migrating our tests to XUnit and Moq which are both better supported in .NET Core. We have been hoping not to have to make this migration, but it might be the only way to get there.

At this time we are not planning to release any betas that would target .NET Core RC1. We are hoping that .NET Core RC2 will come out in a timely fashion.

**Comment by ah-** [comment]
Oh, that sounds great! RC2 is the way to go.

Castle Core just got support for .NET Core, which means NSubstitute is a bit closer. And yes the NUnit situation is a bit annoying, I think I've even seen people put in a wrapping layer that faked NUnit on top of XUnit.

**Comment by tugberkugurlu** [comment]
Good to hear the progress. Closing this as there is a seperate work going on for this.

**Comment by mikeckennedy** [comment]
Hey @rstam what's the status on a C# driver for .NET Core. We are waiting with much anticipation. ;)

**Comment by ah-** [comment]
.NET Core RC2 just got released!

**Comment by gdoron** [comment]
Any update on this one?

**Comment by ahdproduction** [comment]
Any update on this one?

**Comment by alexgwolff** [comment]
I found this : https://github.com/mongodb/mongo-csharp-driver/commit/2c4caba61ed3d6b130288fe3805e7a97c53b3c9f

**Comment by craiggwilson** [comment]
It has been released in beta form on nuget. There is a dependency issue where you'll need to manually resolve certain dependencies until beta2, but all should be working.

**Comment by ahdproduction** [comment]
Thank you for your reply !
I actually tried the 2.3.beta1 but I am unable to solve the manual dependency probleme
Would you have a clue?

**Comment by craiggwilson** [comment]
Yes, you'll need to know which ones are problematic and resolve them. I don't know which one you are hitting. The following are the dependencies that should probably be listed:

<dependency id="NETStandard.Library" version="[1.6.0, )" />
    <dependency id="System.Collections.Specialized" version="[4.0.1, )" />
    <dependency id="System.Diagnostics.TraceSource" version="[4.0.0, )" />
    <dependency id="System.Net.NameResolution" version="[4.0.0, )" />
    <dependency id="System.Net.Security" version="[4.0.0, )" />
    <dependency id="System.Security.Cryptography.Algorithms" version="[4.2.0, )" />
    <dependency id="System.Security.Cryptography.X509Certificates" version="[4.1.0, )" />
    <dependency id="System.Security.SecureString" version="[4.0.0, )" />
    <dependency id="System.Threading" version="[4.0.11, )" />

Not sure how many of these overlap the NETStandardLibrary one.

**Comment by ahdproduction** [comment]
I'm going to try
thank you very much!

**Pull request closed without merging**
